# Day 11

In [194]:
import pandas as pd
import numpy as np
import sys
#np.set_printoptions(threshold=sys.maxsize)


In [195]:
data = np.genfromtxt('input_files/day11_input.txt', delimiter=1, dtype=int)
print(data)

[[4 7 2 1 2 2 4 6 6 3]
 [6 8 7 5 4 1 5 2 7 6]
 [2 7 4 2 4 4 8 4 2 8]
 [4 8 7 8 2 3 1 5 5 6]
 [5 6 8 4 6 4 3 7 4 3]
 [3 5 5 3 6 8 1 8 6 6]
 [4 7 8 8 1 8 3 6 2 5]
 [4 2 5 5 8 5 6 5 3 2]
 [1 4 1 5 8 1 8 7 7 5]
 [2 3 2 6 8 8 6 1 2 5]]


### Part 1

In [197]:
rows, cols = len(data[0]), len(data[1])

def get_adjacent(r, c):
    adjacent = []
    for i, j in ((r-1, c), (r, c-1), (r, c+1), (r+1, c), (r+1, c+1), (r-1,c-1), (r+1, c-1), (r-1,c+1)):
        if 0 <= i < rows and 0 <= j < cols:
            adjacent.append((i, j))
    return adjacent

def flash_cells(x, y, data):
    data[x,y]=0
    adjance_cells = get_adjacent(x, y)
    for coord in get_adjacent(x,y): # increase energy levels of the adjacent cells
        x = coord[0]
        y = coord[1]
        if data[x,y] != 0: # do not increase the counter for already exploded cells
            data[x,y] = data[x,y]+1
    return data

def run_one_step(data):
    data+=1
    count_flash=0
    while np.count_nonzero(data > 9)>0: # keep iterating until all the octopus have exploded
        for x in range(0, len(data[0])):
            for y in range(0, len(data[1])):
                if data[x, y] > 9:
                    #print("flashing octopus", x, y)
                    flash_cells(x, y, data)
                    count_flash+=1
                    #print(data)
    return (data, count_flash)

def run_n_steps(data, n):
    data_run = data.copy()
    count_flash_all=0
    for loop in range(0, n):
        #run_one_step(data)
        count_flash_all+=run_one_step(data_run)[1]
    return data_run, count_flash_all

In [198]:
run_n_steps(data, 100)

(array([[7, 9, 0, 0, 0, 0, 8, 6, 5, 5],
        [9, 3, 5, 0, 0, 4, 2, 8, 6, 5],
        [2, 2, 3, 6, 3, 2, 1, 1, 8, 6],
        [2, 2, 2, 4, 1, 1, 1, 1, 1, 8],
        [3, 3, 2, 3, 5, 1, 1, 1, 1, 1],
        [1, 4, 2, 2, 3, 5, 1, 1, 1, 1],
        [1, 4, 2, 2, 2, 3, 5, 1, 1, 1],
        [8, 3, 2, 2, 2, 2, 3, 6, 1, 1],
        [6, 8, 2, 2, 2, 2, 3, 6, 3, 2],
        [5, 6, 8, 2, 2, 2, 3, 0, 0, 2]]),
 1675)

### Part 2

In [201]:
def check_if_all_flashing(data):
    data_run = data.copy()
    n = 0
    while np.count_nonzero(data_run > 0) > 0:
        run_one_step(data_run)
        n+=1
    return data_run, n

In [202]:
check_if_all_flashing(data)

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 515)