# Day 15

In [1]:
import pandas as pd
import numpy as np
import sys
#np.set_printoptions(threshold=sys.maxsize)

In [2]:
with open('input_files/day15_input.txt') as f:
    lines = f.read().splitlines()

In [3]:
lines

['1163751742',
 '1381373672',
 '2136511328',
 '3694931569',
 '7463417111',
 '1319128137',
 '1359912421',
 '3125421639',
 '1293138521',
 '2311944581']

In [4]:
data = np.genfromtxt('input_files/day15_input.txt', delimiter=1, dtype=int)
print(data)

[[1 1 6 3 7 5 1 7 4 2]
 [1 3 8 1 3 7 3 6 7 2]
 [2 1 3 6 5 1 1 3 2 8]
 [3 6 9 4 9 3 1 5 6 9]
 [7 4 6 3 4 1 7 1 1 1]
 [1 3 1 9 1 2 8 1 3 7]
 [1 3 5 9 9 1 2 4 2 1]
 [3 1 2 5 4 2 1 6 3 9]
 [1 2 9 3 1 3 8 5 2 1]
 [2 3 1 1 9 4 4 5 8 1]]


In [11]:
start = [0,0]
data[0,2]

6

In [29]:
heapq.heappop([(1, (1, 0)), (1, (0, 1))])

(1, (1, 0))

In [37]:
import sys
import heapq

grid = [list(map(int, row)) for row in open("input_files/day15_input.txt").read().split('\n')]
rows, cols = len(grid), len(grid[0])

deltas = [(-1, 0), (0, -1), (1, 0), (0, 1)]

risk = {(i, j): sys.maxsize for i in range(rows) for j in range(cols)}
queue = [(0, (0, 0))]

while (queue):
    current_risk, position = heapq.heappop(queue)
    print(queue)
    print("here", current_risk, position)
    for di, dj in deltas:
        ni, nj = di + position[0], dj + position[1]
        neighbor_position = (ni, nj)
        if (neighbor_position in risk):
            print("position next", ni, nj, "value", grid[ni][nj])
            new_risk = current_risk + grid[ni][nj]
            if (new_risk < risk[neighbor_position]):
                print(new_risk, risk[neighbor_position])
                risk[neighbor_position] = new_risk
                heapq.heappush(queue, (new_risk, neighbor_position))
                print("new queue", queue)
print(risk)
print(risk[(rows - 1, cols - 1)])

[]
here 0 (0, 0)
position next 1 0 value 1
1 9223372036854775807
new queue [(1, (1, 0))]
position next 0 1 value 1
1 9223372036854775807
new queue [(1, (0, 1)), (1, (1, 0))]
[(1, (1, 0))]
here 1 (0, 1)
position next 0 0 value 1
2 9223372036854775807
new queue [(1, (1, 0)), (2, (0, 0))]
position next 1 1 value 3
4 9223372036854775807
new queue [(1, (1, 0)), (2, (0, 0)), (4, (1, 1))]
position next 0 2 value 6
7 9223372036854775807
new queue [(1, (1, 0)), (2, (0, 0)), (4, (1, 1)), (7, (0, 2))]
[(2, (0, 0)), (7, (0, 2)), (4, (1, 1))]
here 1 (1, 0)
position next 0 0 value 1
position next 2 0 value 2
3 9223372036854775807
new queue [(2, (0, 0)), (3, (2, 0)), (4, (1, 1)), (7, (0, 2))]
position next 1 1 value 3
[(3, (2, 0)), (7, (0, 2)), (4, (1, 1))]
here 2 (0, 0)
position next 1 0 value 1
position next 0 1 value 1
[(4, (1, 1)), (7, (0, 2))]
here 3 (2, 0)
position next 1 0 value 1
position next 3 0 value 3
6 9223372036854775807
new queue [(4, (1, 1)), (7, (0, 2)), (6, (3, 0))]
position next 2 

In [39]:
from queue import PriorityQueue

with open("input_files/day15_input.txt") as f:
    matrix = [list(map(int, line)) for line in f.read().splitlines()]


# solved using priority queue
def solve_dis(m):
    h, w = len(m), len(m[0])
    pq = PriorityQueue()
    # Add starting position in priority queue
    pq.put((0, (0, 0)))
    visited = {(0, 0), }
    while pq:
        curr_risk, (i, j) = pq.get()
        # Once we reach the end of the matrix, we can stop and return the risk
        if i == h - 1 and j == w - 1:
            return curr_risk
        for x, y in [(i + 1, j), (i - 1, j), (i, j + 1), (i, j - 1)]:
            if 0 <= x < h and 0 <= y < w and (x, y) not in visited:
                weight = m[x][y]
                pq.put((curr_risk + weight, (x, y)))
                visited.add((x, y))


def make_big_matrix():
    # Using dict to map weights {1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 1}
    d = {i: j % 10 if j % 10 != 0 else 1 for i, j in zip(range(1, 10), range(2, 11))}
    big_matrix = [lst.copy() for lst in matrix]
    for _ in range(4):
        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                big_matrix[i].append(d[big_matrix[i][j + len(matrix) * _]])
    for _ in range(4):
        for i in range(len(matrix)):
            new_list = list()
            for j in range(len(big_matrix[0])):
                new_list.append(d[big_matrix[i + len(matrix) * _][j]])
            big_matrix.append(new_list)
    return big_matrix


print(f'Part 1 : {solve_dis(matrix)}')
print(f'Part 2 : {solve_dis(make_big_matrix())}')

Part 1 : 748
Part 2 : 3045
