# Day 5


You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review. For example:
<code>
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
</code>
Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.
For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

So, the horizontal and vertical lines from the above list would produce the following diagram:
<code>
.......1..
..1....1..
..1....1..
.......1..
.112111211
..........
..........
..........
..........
222111....
</code>
In this diagram, the top left corner is 0,0 and the bottom right corner is 9,9. Each position is shown as the number of lines which cover that point or . if no line covers that point. The top-left pair of 1s, for example, comes from 2,2 -> 2,1; the very bottom row is formed by the overlapping lines 0,9 -> 5,9 and 0,9 -> 2,9.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.

### Part 1

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?

In [9]:
import pandas as pd
import numpy as np
import sys
#np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=50)


In [23]:
pwd

'C:\\Users\\incar\\Documents\\GitHub\\advent_of_code_2021'

#### Load data with proper separators

In [25]:
data = pd.read_csv('input_files/day5_input.txt',header = None, delimiter = ",|->", names = ["x1","y1", "x2", "y2"],engine='python')
print(data.head())

    x1   y1   x2   y2
0  445  187  912  654
1  820   46   25  841
2  216  621  458  379
3  955  898   67   10
4  549  572  549  520


#### Initialize empty diagram

In [12]:
def initialize_diagram(data):
    max_x = data[['x1', 'x2']].max().max()
    max_y = data[['y1', 'y2']].max().max()
    min_x = data[['x1', 'x2']].min().min()
    min_y = data[['y1', 'y2']].min().min()

    diagram = np.zeros(shape=(max_x+1,max_y+1))
    #diagram = np.where(diagram == 0, ".", diagram)
    return diagram

diagram = initialize_diagram(data)
diagram

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### Consider only horizontal/vertical lines

In [13]:
lines_data = data[(data.x1 == data.x2)|(data.y1 == data.y2)].reset_index(drop=True)
lines_data

x1   y1   x2   y2
0    549  572  549  520
1    729  698  338  698
2    381  840  381  409
3     80  467   80   48
4    132  197  132   92
..   ...  ...  ...  ...
319  796  213  796  407
320  775  471  272  471
321   26  138  344  138
322  635  518  915  518
323  727  365  727  216

[324 rows x 4 columns]

#### Prepare functions

In [14]:
def draw_line(diagram, line):
    x_start = min(line.x1, line.x2)
    x_end = max(line.x1, line.x2)
    y_start = min(line.y1, line.y2)
    y_end = max(line.y1, line.y2)
    print("processing coordinates:",str(x_start),str(y_start), str(x_end), str(y_end))
    if x_start != x_end:
        for i in range(x_start, x_end+1):
            #print("Changing x of "+str(i))
            #print(diagram[y_end, i])
            diagram[y_end, i]+=1
            
        #print(diagram) #[x_start:x_end, y_end])
    elif y_start != y_end:
        for i in range(y_start, y_end+1):
            #print("Changing y of "+str(i))
            #print(diagram[i, x_end])
            diagram[i, x_end]+=1
        #print(diagram) #[x_end, y_start:y_end])
    return diagram

def update_diagram(lines_data, diagram):
    updated_diagram = diagram
    for i in range(0, len(lines_data)):
        line=lines_data.iloc[i]  
        updated_diagram = draw_line(updated_diagram, line)    
    return updated_diagram

In [15]:
updated_diagram = update_diagram(lines_data, diagram)

processing coordinates: 549 520 549 572
processing coordinates: 338 698 729 698
processing coordinates: 381 409 381 840
processing coordinates: 80 48 80 467
processing coordinates: 132 92 132 197
processing coordinates: 343 96 343 710
processing coordinates: 503 56 804 56
processing coordinates: 60 206 599 206
processing coordinates: 474 920 702 920
processing coordinates: 583 579 969 579
processing coordinates: 604 66 897 66
processing coordinates: 330 49 949 49
processing coordinates: 714 132 908 132
processing coordinates: 800 51 800 61
processing coordinates: 179 202 179 242
processing coordinates: 529 757 529 838
processing coordinates: 288 953 393 953
processing coordinates: 245 981 576 981
processing coordinates: 347 240 347 928
processing coordinates: 534 257 950 257
processing coordinates: 539 274 539 327
processing coordinates: 630 670 722 670
processing coordinates: 28 167 28 489
processing coordinates: 186 59 700 59
processing coordinates: 121 186 670 186
processing coordin

In [16]:
updated_diagram

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### Count cells with value greater or equal 2

In [17]:
print(np.count_nonzero(updated_diagram >= 2))

5197


### Part 2

Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Because of the limits of the hydrothermal vent mapping system, the lines in your list will only ever be horizontal, vertical, or a diagonal line at exactly 45 degrees. In other words:

An entry like 1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
An entry like 9,7 -> 7,9 covers points 9,7, 8,8, and 7,9.
Considering all lines from the above example would now produce the following diagram:
<code>
1.1....11.
.111...2..
..2.1.111.
...1.2.2..
.112313211
...1.2....
..1...1...
.1.....1..
1.......1.
222111....
</code>

You still need to determine the number of points where at least two lines overlap. In the above example, this is still anywhere in the diagram with a 2 or larger - now a total of 12 points.

Consider all of the lines. At how many points do at least two lines overlap?

#### Select also diagonal lines (y1-y2==x1-x2)

In [18]:
lines_data = data[(data.x1 == data.x2)|(data.y1 == data.y2)|(abs(data.y1-data.y2)==abs(data.x1-data.x2))].reset_index(drop=True)
lines_data

x1   y1   x2   y2
0    445  187  912  654
1    820   46   25  841
2    216  621  458  379
3    955  898   67   10
4    549  572  549  520
..   ...  ...  ...  ...
495   55  948  980   23
496  775  471  272  471
497   26  138  344  138
498  635  518  915  518
499  727  365  727  216

[500 rows x 4 columns]

#### Updated functions

In [19]:
def draw_line(diagram, line):
    x_start = line.x1
    x_end = line.x2
    y_start = line.y1
    y_end = line.y2
    print("processing coordinates:",str(x_start),str(y_start), str(x_end), str(y_end))
    y_dir = 1 if y_start<y_end else -1
    x_dir = 1 if x_start<x_end else -1
    
    if (x_start != x_end) & (y_start == y_end):
        for i in range(0, (x_end-x_start)*x_dir+1):
            diagram[y_end, x_start+(i*x_dir)]+=1
    elif (y_start != y_end) & (x_start == x_end):
        for i in range(0, (y_end-y_start)*y_dir+1):
            diagram[y_start+(i*y_dir), x_end]+=1
    elif (y_start != y_end) & (x_start != x_end):
        for i in range(0, (y_end-y_start)*y_dir+1):
             diagram[y_start+(i*y_dir), x_start+(i*x_dir)]+=1
    #print(diagram)
    return diagram

def update_diagram(lines_data, diagram):
    updated_diagram = diagram
    for i in range(0, len(lines_data)):
        line=lines_data.iloc[i]  
        updated_diagram = draw_line(updated_diagram, line)    
    return updated_diagram

In [20]:
diagram = initialize_diagram(data)
diagram

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
updated_diagram = update_diagram(lines_data, diagram)
updated_diagram

processing coordinates: 445 187 912 654
processing coordinates: 820 46 25 841
processing coordinates: 216 621 458 379
processing coordinates: 955 898 67 10
processing coordinates: 549 572 549 520
processing coordinates: 796 107 109 794
processing coordinates: 729 698 338 698
processing coordinates: 11 987 968 30
processing coordinates: 381 840 381 409
processing coordinates: 80 467 80 48
processing coordinates: 132 197 132 92
processing coordinates: 343 96 343 710
processing coordinates: 42 854 346 550
processing coordinates: 503 56 804 56
processing coordinates: 599 206 60 206
processing coordinates: 702 920 474 920
processing coordinates: 496 790 223 517
processing coordinates: 969 579 583 579
processing coordinates: 897 66 604 66
processing coordinates: 484 754 640 910
processing coordinates: 330 49 949 49
processing coordinates: 908 132 714 132
processing coordinates: 517 153 97 573
processing coordinates: 317 865 678 504
processing coordinates: 800 61 800 51
processing coordinates

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### Count cells with value greater or equal 2

In [22]:
print(np.count_nonzero(updated_diagram >= 2))

18605
